-- WindyPeak v.226 modular configuration.
-- Change shared timings/ranges here instead of editing Main.lua.

return {
    VERSION = "v.226",

    WEAPON_SHOP_ARRIVE_DELAY = 0.35,
    WEAPON_VERIFY_TIMEOUT = 2.50,
    WEAPON_PURCHASE_RETRY_DELAY = 3.00,
    HOTBAR_REBUILD_DELAY = 0.75,
    WEAPON_SYNC_WAIT_TIMEOUT = 3.00,
    MOVEMENT_LOCK_WAIT_TIMEOUT = 1.50,
    CONTROLLER_ERROR_RETRY_DELAY = 0.50,

    FARM_HEIGHT = 6,
    FARM_POSITION_MODE = "Above",
    HIT_DELAY = 0.20,
    MAX_COMBO_HIT = 4,
    COMBO_END_DELAY = 0.20,

    COMBAT_STALL_COMBO_LIMIT = 2,
    COMBAT_RECOVERY_COOLDOWN = 2.00,

    TARGET_SWITCH_DELAY = 0.25,
    MAX_ATTACK_DISTANCE = 8,

    AUTO_SKILL_RETRY_DELAY = 0.75,
    AUTO_SKILL_INTERVAL = 1.00,
    AUTO_SKILL_MAX_DISTANCE = 10,

    QUEST_ARRIVE_DELAY = 0.30,
    QUEST_ACCEPT_RETRY_DELAY = 1.00,
    QUEST_AFTER_ACCEPT_DELAY = 0.15,
    QUEST_VERIFY_TIMEOUT = 0.65,
    QUEST_UI_POLL_DELAY = 0.05,
    QUEST_OLD_UI_CLEAR_TIMEOUT = 5.00,
    QUEST_COMPLETE_DELAY = 8.00,
    QUEST_PROGRESS_DEATH_HOLD = 0.40,
    QUEST_PANEL_CLEAR_DEATH_WINDOW = 2.00,
    QUEST_STREAM_WAIT_TIMEOUT = 5.00,
    QUEST_WAYPOINT_FOLDER = "WindyPeak",
    QUEST_WAYPOINT_FILE = "WindyPeak/quest_npc_waypoints.json",

    BOSS_WAYPOINT_FOLDER = "WindyPeak",
    BOSS_WAYPOINT_FILE = "WindyPeak/boss_waypoints.json",
    BOSS_WAYPOINT_SCAN_DELAY = 2.00,
    BOSS_STREAM_WAIT_TIMEOUT = 4.00,
    BOSS_STREAM_HOVER_HEIGHT = 60,
    BOSS_STREAM_HOVER_STEP = 0.05,
    RESPAWN_RECOVERY_DELAY = 1.25,

    BOSS_LOOT_CHEST_RADIUS = 45,
    BOSS_LOOT_CHEST_WAIT = 6.00,
    BOSS_LOOT_DROP_WAIT = 12.00,
    BOSS_LOOT_SETTLE_DELAY = 2.00
}
