-- WindyPeak v.191 modular configuration.
-- Change shared timings/ranges here instead of editing Main.lua.

return {
    VERSION = "v.191",

    WEAPON_SHOP_ARRIVE_DELAY = 0.35,
    WEAPON_VERIFY_TIMEOUT = 2.50,
    WEAPON_PURCHASE_RETRY_DELAY = 3.00,

    FARM_HEIGHT = 6,
    HIT_DELAY = 0.20,
    MAX_COMBO_HIT = 4,
    COMBO_END_DELAY = 0.20,

    COMBAT_STALL_COMBO_LIMIT = 2,
    COMBAT_RECOVERY_DELAY = 0.15,
    COMBAT_RECOVERY_COOLDOWN = 2.00,

    TARGET_SWITCH_DELAY = 0.25,
    MAX_ATTACK_DISTANCE = 8,

    QUEST_ARRIVE_DELAY = 0.30,
    QUEST_ACCEPT_RETRY_DELAY = 1.00,
    QUEST_AFTER_ACCEPT_DELAY = 0.15,
    QUEST_VERIFY_TIMEOUT = 0.65,
    QUEST_UI_POLL_DELAY = 0.05,
    QUEST_OLD_UI_CLEAR_TIMEOUT = 5.00,
    QUEST_COMPLETE_DELAY = 8.00,
    QUEST_PROGRESS_DEATH_HOLD = 0.40,
    QUEST_PANEL_CLEAR_DEATH_WINDOW = 2.00,

    BOSS_LOOT_CHEST_RADIUS = 45,
    BOSS_LOOT_CHEST_WAIT = 6.00,
    BOSS_LOOT_DROP_WAIT = 12.00,
    BOSS_LOOT_SETTLE_DELAY = 2.00
}
